### ISSUE TITLE
ARM Version?

### ISSUE THREAD

**Issue by Okoyl** [TimDettmers/bitsandbytes#106]
I noticed that this libary uses SSE instructions, And I wonder if there is any plan to support other CPU architectures? or implement everything in plain c++ instead of special instructions just to enable it to compile on any architecture?

**Comment by TimDettmers** [comment]
Thanks for noting this and brining it to my attention! The code itself does not require SSE but by default, I compile with SSE. I think you should be able to compile without SSE locally. Could you try that and let me know if it works?

Otherwise, for future releases, I can compile a non-SSE CPU version so its accessible via pip.
