### ISSUE TITLE
Bitsandbytes cannot find CUDA libraries

### ISSUE THREAD

**Issue by kevin-guimard-ext** [TimDettmers/bitsandbytes#1106]
### System Info

Windows 10
Python 3.10.3

### Reproduction

I installed bitsandbytes on Windows this way:

> pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl

But I get the following error when I try to import the lib:

> UserWarning: C:\Users\kevguima\AppData\Local\anaconda3\envs\genai did not contain ['cudart64_110.dll', 'cudart64_12.dll'] as expected! Searching further paths...
>   warn(msg)
> The following directories listed in your path were found to be non-existent: {WindowsPath('/EMED2ADC01')}
> The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/kevguima/Documents/WindowsPowerShell/Modules')}
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
> DEBUG: Possible options found for libcudart.so: set()
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.dll. Maybe you need to compile it from source?
> CUDA SETUP: Defaulting to libbitsandbytes_cpu.dll...
...

Though, I properly installed the CUDA runtime and the file cudart64_12.dll can be found in my Anaconda environment:
C:\Users\kevguima\AppData\Local\anaconda3\envs\genai\Lib\site-packages\nvidia\cuda_runtime\bin

I add that torch can locate it (i.e. torch.cuda.is_available() returns True).

So, what should be done so that bitsandbytes could locate CUDA libraries?

### Expected behavior

1) I expect bitsandbytes to be properly ported to Windows (many issues already report this problem)
2) I expect bitsandbytes to properly detect the CUDA libraries, or to document the way to configure the paths

**Comment by kevin-guimard-ext** [comment]
As an update, I set the variable LD_LIBRARY_PATH to the CUDA installation path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin" and bitsandbytes finds it but still doesn't find the required libraries inside...

> C:\Users\kevguima\bitsandbytes\bitsandbytes\cuda_setup\main.py:183: UserWarning: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin did not contain ['cudart64_110.dll', 'cudart64_12.dll'] as expected! Searching further paths...

I suspect the issue to be the absence of the 'cudart64_110.dll' file in the CUDA installation directory. Do you confirm?

**Comment by matthewdouglas** [comment]
@kevin-guimard-ext The `bitsandbytes` distribution you've installed is from a third-party so it's hard to say. However, it does look like you've got PyTorch built with CUDA 11.8 installed, but also trying to load libraries from a CUDA Toolkit v12.3, so that's why things aren't lining up. Normally you shouldn't really even need the CUDA Toolkit installed.

You should find the cudart64_110.dll somewhere included with your PyTorch installation, e.g. in `torch/lib`. Maybe you can get away with using `os.add_dll_directory()` to point to the right location as `LD_LIBRARY_PATH` doesn't do anything for Windows.

An official Windows build will be coming rather soon. Until then, you could also try [compiling from source](https://huggingface.co/docs/bitsandbytes/main/en/installation?OS+system=Windows).

**Comment by ELMatero6** [comment]
About how soon @matthewdouglas ?

**Comment by kevin-guimard-ext** [comment]
@matthewdouglas Thanks for your reply. I was about to apply your suggestions when I found out that everything already worked... My computer reboot made miracles. :) So please post a Windows version soon in 0.41.3+ so that it could support 4-bit models.

**Comment by matthewdouglas** [comment]
@ELMatero6 @kevin-guimard-ext FYI: [v0.43.0](https://github.com/TimDettmers/bitsandbytes/releases/tag/0.43.0) has been released, which includes support for Windows!

**Comment by kevin-guimard-ext** [comment]
Awesome! Thank you @matthewdouglas.

**Comment by ELMatero6** [comment]
@matthewdouglas You the man matthew! I would never have noticed!

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗

**Comment by BimwerxNZ** [comment]
This is what I get after installing bitsandbytes on win: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.

Why is this such a pain!? Compiling from source produces a string of other issues again... argh!

**Comment by RETR0-OS** [comment]
> This is what I get after installing bitsandbytes on win: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
> 
> Why is this such a pain!? Compiling from source produces a string of other issues again... argh!

+1

This is a really big problem is that I built an entire package around model fine-tuning and quantization. The thing is, everything worked fine in my package environment, but when I package it up as a wheel for my users, the cuda dll files are again missing in the pip installation of my package for bitsandbytes. The biggest problem is that the official wheel file I used to install the dependency in my development environment shows a 404 now.

Here is the broken link (in case this helps fix things:

`https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.44.1.dev0-py3-none-manylinux_2_24_x86_64.whl`
