### ISSUE TITLE
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes`

### ISSUE THREAD

**Issue by bhavnicksm** [TimDettmers/bitsandbytes#230]
While running the example notebook, I get this error saying loading in float16 instead of int8.
It doesn't load in  mixed 8bit no matter what I tried.

[https://colab.research.google.com/github/huggingface/blog/blob/main/notebooks/HuggingFace_int8_demo.ipynb#scrollTo=9VOMsHmY37Sx]

**Comment by younesbelkada** [comment]
Hey @bhavnicksm 
Actually the warning just states that the `torch_dtype` attribute of the model will be set to `torch.float16` which is expected. This is because the int8 layers always output float16 hidden states, but in fact the converted layers are still in int8 . In the demo there are few instrcutions on how to check that the conversion has been successfull.

**Comment by bhavnicksm** [comment]
Oh, I see. It was a my misunderstanding. Thanks @younesbelkada! (^^)
