### ISSUE TITLE
Is it possible to use int8 for other task?

### ISSUE THREAD

**Issue by haritsahm** [TimDettmers/bitsandbytes#29]
From your paper and blog post, the quantization was tested using transformers. Is it possible to use the library for objet detection models and will it experience performance degradation?

**Comment by TimDettmers** [comment]
I have not tested this, but it should be possible for vision transformers. I known already from data that vision transformers behave the very same in terms of outliers than language model transformers. As such, I think it will work.

However, it will not straightforwardly work for convolutional networks, since the current implementation just supports the replacement of `torch.nn.Linear` layers and not convolutional layers with the 8-bit equivalent.
