### ISSUE TITLE
my error

### ISSUE THREAD

**Issue by Leekt222** [TimDettmers/bitsandbytes#298]
CUDA SETUP: Loading binary C:\Users\user\Documents\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Users\user\Documents\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Traceback (most recent call last):
  File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\server.py", line 347, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
Press any key to continue . . .

**Comment by TimDettmers** [comment]
Thank you for your report. This does not seem to be a problem with bitsandbytes, because bitsandbytes loads without any error. The error lies with another library. It seems the problem is related to the module `llama_inference_offload` which is not related to bitsandbytes. Please file an issue here: https://github.com/qwopqwop200/GPTQ-for-LLaMa
