### ISSUE TITLE
Memory usage with 8bit optimizer for a problem of classification

### ISSUE THREAD

**Issue by int8** [TimDettmers/bitsandbytes#407]
Hello, 

I work with the following example code (which is really hello world text classification from hf docs) 

```
from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer 
import bitsandbytes as bnb 
import torch 

dataset = load_dataset("yelp_review_full")
tokenizer = AutoTokenizer.from_pretrained(
    "roberta-base"
)

def tokenize_function(examples):
    return tokenizer(
        examples["text"], 
        padding="max_length", 
        truncation=True
    )

tokenized_datasets = dataset.map(tokenize_function, batched=True)
small_train_dataset = tokenized_datasets["train"].shuffle(
    seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(
    seed=42).select(range(1000))

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base", 
    num_labels=5, 
    device_map="auto"
)

training_args = TrainingArguments(
    "output_dir", per_device_train_batch_size=24
)

optimizer_8bit = bnb.optim.Adam8bit(
    model.parameters()
)

optimizer_32bit = torch.optim.Adam(
    model.parameters()
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    optimizers=(optimizer_8bit, None)
    #optimizers=(optimizer_32bit, None)
)
trainer.train()
```

I use two optimizers, one is `Adam8bit` from `bnb.optim`, the other one is regular 32bit `Adam` from `torch.optim` 

I was expecting significantly less memory consumed with 8bit Adam, but I don't see it, I rather see 10% less memory consumption,

am I doing it it wrong? or it is actually expected? if it is expected - why? 

thanks

**Comment by yeeeqichen** [comment]
Same problem here, when I pass the `bnb.optim.Adam8bit` in to HF.trainer, the memory usage is still the same as HF.trainer's default setting.

**Comment by yeeeqichen** [comment]
> i also tried a Classification task with Bloom-560m PEFT and Lora for a dataset with 512 sequence length, per_device_train_batch_size=32: Consuming 36GB GPU RAM
> 
> I enabled BnB thinking i would get a reduction, but it actually increased RAM to 39GB
> 
> not sure why

@maadnfritz 
After several experiments, I have the following findings:

- If the `PEFT` setting is enabled (lora or qlora), there won't be a big difference regarding to the GPU memory usage after enabling the `adam_8bit`, because we only have little trainable parameters (e.g., 0.1% ~ 1%). So under `PEFT` setting, the optimizer state will only contribute little to the total GPU memory usage, the consumed GPU memory are mainly used for the model weight as well as the activations.
- But if we finetune the model under the `FULL-training` setting, the optimizer state will consume most of the GPU memory, if we turn on the `adam_8bit` here, we are expected to see significantly less GPU memory consumed.
