### ISSUE TITLE
Meaning for the "Int8 absmax row-wise + decomposition" combination in paper ?

### ISSUE THREAD

**Issue by frankang** [TimDettmers/bitsandbytes#43]
Hi, I have problem understanding the "Int8 absmax row-wise + decomposition" entry in Table 1. Does it mean "Absmax LLM.int8() (row-wise + decomp)" ? Because it does not contain the "LLM.int8()" keyword, I'm wondering if it refers to some combination else.
Thanks!
![image](https://user-images.githubusercontent.com/16100899/192259807-8d285d2f-a21e-4848-a4dc-d80fdefb7b59.png)

**Comment by TimDettmers** [comment]
`LLM.int8()` does stand for the combination of vector-wise quantization _and_ mixed precision decomposition. Since row-wise quantization is used, it is not a variant of `LLM.int8()`. 

Row-wise quantization only performs vector quantization of the input tensor (mini-batch/hidden state) while full vector-wise quantization also performs vector quantization on the weight matrix.

**Comment by frankang** [comment]
Thank you for the explanation.
