### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by zabir-nabil** [TimDettmers/bitsandbytes#450]
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

Fixed by adding the latest g++ path in makefile.

**Comment by lucenzhong** [comment]
hello, I meet the same bug.  Can you explain more about how to fix this? I tried to use '-std=c++11' instead of '-std=c++14' in the makefile, it didn't work. What did you mean by "the latest g++ path" ? I use the command "which g++" to get g++ path, and the result is "/usr/bin/g++", I don't know whats going on. 
Looking forward to your reply.

**Comment by xf4fresh** [comment]
> I solved it by upgrading my GCC version and putting the updated path in Makefile.

Can you kindly tell me which version you upgraded to?

**Comment by zabir-nabil** [comment]
I think it was 10.3.0
