### ISSUE TITLE
Strange Model Zero-Shot Inference Performance After Applying LLM.int8() Quantization

### ISSUE THREAD

**Issue by zjc664656505** [TimDettmers/bitsandbytes#511]
### Issue

Dear bitsandbytes commnity,

Recently, I'm working on post-training quantization research project. I applied the LLM.int8() quantization strategy on bloom series of models first in my research project. Here is the result of it:

![Screenshot from 2023-06-11 18-25-29](https://github.com/TimDettmers/bitsandbytes/assets/45058866/3a65890e-30f7-41e1-b60d-42a867361256)

As you can see from this result, the inference time is not decreasing after the model parameter size is reduced below 3 billion with quantization applied. Also, it's very strange to see only bloom3b has a significant zero-shot performance drop after int8 quantization is applied. 

If it's possible, could anyone help me with explaining this result?

Thanks a lot!

### Hardware
1. CUDA version 12.0
2. GPU: Nvidia A6000

### Software
1. Pytorch 2.0.1

**Comment by TimDettmers** [comment]
The kernels for Int8 were designed for training and not inference, so that is why its slow. In particular its slow for small models since the smaller Int8 matrices cannot fully saturate the GPU and the overhead of quantization is problematic.

I am not sure what went wrong with the bloom 3B model, though. It might be that some outliers are not properly detected. In that case, you can try play around by decreasing the `llm_int8_threshold` variable (if you use this through HF transformers).  or the `threshold`  variable in the `Linear8bitLt` module.
