### ISSUE TITLE
kQuantizeBlockwise dereferences a null pointer when invoked from quantize_4bit

### ISSUE THREAD

**Issue by ekmett** [TimDettmers/bitsandbytes#536]
The python side functional.py `quantize_4bit` function passes along a null pointer for `code`.

Later that gets plumbed through to `quantizeBlockwise` and then to the `kQuantizeBlockwise` kernel, where it is blindly dereferenced and copied into `smem_code`. This dereferences a null pointer and should probably handled correctly. (I'm getting crashes in that kernel on A100s, and haven't been able to run it to ground further than that.)

**Comment by TimDettmers** [comment]
Do you have a script that can reproduce this error. I do not think the issue is with `code`. The two relevant lines are not compiled for 4-bit kernels and only for 8-bit  kernels where they are always not `null`.

quantize: https://github.com/TimDettmers/bitsandbytes/blob/main/csrc/kernels.cu#L749
dequantize: https://github.com/TimDettmers/bitsandbytes/blob/main/csrc/kernels.cu#L867

Let me know if I am missing something.
