### ISSUE TITLE
What is the relation between bitsandbytes and gptq?

### ISSUE THREAD

**Issue by siddhsql** [TimDettmers/bitsandbytes#539]
Hello, I would like to understand what is the relation or difference between bitsandbytes and gptq e.g., [this](https://github.com/qwopqwop200/GPTQ-for-LLaMa)? as I understand so far, bnb does quantization of an unquantized model at runtime whereas gptq is used to load an already quantized model in gptq format. is that correct? would it be also correct to say one should use one or the other (i.e., either bnb or gptq) but not both simultaneously? and both of these do require GPU - specifically CUDA? thanks for any clarification.

**Comment by TimDettmers** [comment]
GPTQ uses Integer quantization + an optimization procedure that relies on an input mini-batch to perform the quantization. Once the quantization is completed, the weights can be stored and reused. 

Bitsandbytes can perform integer quantization but also supports many other formats. However, bitsandbytes does not perform an optimization procedure that involves an input mini-batch to perform quantization. That is why it can be used directly for any model. 

However, it is less precise than GPTQ since information of the input data helps with quantization.

Reopen this issue if things are still unclear or you have more questions regarding the difference between GPTQ and bitsandbytes.
