### ISSUE TITLE
When reading the source code, there are many definitions that I don't understand.

### ISSUE THREAD

**Issue by dingjingzhen** [TimDettmers/bitsandbytes#540]
Can you explain what each of CA, CAt, SCA, SCAt, coo_tensorA, CB, state.CBt, state.SCB, state.SCBt,coo_tensorB means?

**Comment by DavidFarago** [comment]
I read https://arxiv.org/pdf/2208.07339.pdf and asked myself the whole time how VRAM can be reduced since the outliers depend on the input X, so I need FP16 for all weights. 

Then I looked at https://huggingface.co/blog/hf-bitsandbytes-integration and found the explanation 

> You might also wonder how to retrieve the FP16 weights in order to perform the outlier MatMul in fp16? You can simply do:
> 
> ```(int8_model[0].weight.CB * int8_model[0].weight.SCB) / 127```

Since `.CB` and `.SCB` comes out of nowhere, I searched the codebase, and both `.CB` and `.SCB` occur everywhere. And nowhere with explanation :( 

So after spending a lot of time, I still do not understand at all the purpose of LLM.int8(), i.e. how it can safe VRAM. 

So an explanation of `.CB` and `.SCB` would be extremely helpful.

**Comment by TimDettmers** [comment]
So CA mean quantized A. SCA means the _quantization state_ that belongs to CA. For dequantization both SCA and CA is needed. CAt is the quantization state of A^T (transposed) indicating that column-wise quantization turns into row-wise quantization and vice versa (see https://arxiv.org/abs/2208.07339 for more info on row/column-wise quantization). 

coo_tensorB is a coordinate-wise sparse tensor that indicates where outliers are present. Only part of it is used now. In the past it was used to perform a custom sparse matrix multiplication of the outliers in the matrix, but since I discovered that outliers are highly structured, the sparse matrix multiplication was no longer needed. 

I hope this clarifies everything. If you have more questions please reopen the issue.
