### ISSUE TITLE
running the tests with matmul disabled during build causes tests to terminate prematurely

### ISSUE THREAD

**Issue by Thomas-MMJ** [TimDettmers/bitsandbytes#78]
` CUDA_VERSION=118 make cuda11x_nomatmul`

results in 

`pytest-3 tests`

terminating prematurely (about 7% through test_autograd.py ) at.

`tests/test_autograd.py::test_matmullt[dim1_36_dim2_69_dim3_47_dim4_68_func_matmul_dtype_torch.float16_requires_grad_TTT_transpose_NT_decomp_0.0_has_fp16_weights_True_has_bias_True]`

building with

`CUDA_VERSION=118 make`

and the tests run to completion.  Note that the termination just dumps you directly to the prompt, it doesn't fail it just exits out of the pytest-3 without finishing.

**Comment by TimDettmers** [comment]
I worked on this before, but it seems that my solution still did not work. Could you have a look at this and try to fix it? It would help others that develop on non-Turing/non-Ampere GPUs. Since we will soon have a patch that works will all GPUs, this will be an important addition.

The main problem is that,  if we do not compile the cublasLt functions, then we can either
1. Remove the C extension functions, and then we need to adjust all references to that function in python files to not run into a segfault
2. Do not remove the C extension functions, in this case we want to throw an error when the cublasLt function is called without cublasLt support.

Currently, (2) is implemented in [ops.cu](https://github.com/TimDettmers/bitsandbytes/blob/main/csrc/ops.cu#L402).
