### ISSUE TITLE
[Feature Request] PLEASE support Windows

### ISSUE THREAD

**Issue by d8ahazard** [TimDettmers/bitsandbytes#800]
Hey there! Love your work. As the developer of the dreambooth extension for Auto1111, I use it a lot.

However, ever since I've been supporting the extension, one of the biggest headaches and holdups has been dealing with getting BNB to work for Windows. Whether it's packaging custom binaries and hacking the default .38 install or pulling the code from one of your contributor's repositories - there has always had to be a workaround in place to support windows, despite there existing obvious workarounds to make it work.

So, I'm imploring you...could you please add support for Windows to the native pypi package? It'd make a lot of people happy, and it'd spare me a lot of headaches every time a new update is released. If you need a regular tester or someone to run builds - I'm happy to help out.

**Comment by d8ahazard** [comment]
This is not complete.

**Comment by Titus-von-Koeller** [comment]
Thanks @d8ahazard for the kind words and offer of support! We finally managed to get everything working now. Let us know if it solved the issue.

---

Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗

**Comment by d8ahazard** [comment]
YASSSDSDDDSSSSSSSSSSSSS!!!!!!!
