### ISSUE TITLE
CUDASetup generate cryptic error when there is URL in environment variables

### ISSUE THREAD

**Issue by wfjsw** [TimDettmers/bitsandbytes#820]
CUDASetup will attempt to access http/https links in a way that is not supposed to, thus generating exceptions in weird locations.

![136f2aea5d70e9c05fe21e079f204333](https://github.com/TimDettmers/bitsandbytes/assets/2220320/1f61a5a4-18fb-471e-b02f-8a0f5e391856)

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by wfjsw** [comment]
still relevant

**Comment by wfjsw** [comment]
still relevant

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
