### ISSUE TITLE
`bfloat16` support

### ISSUE THREAD

**Issue by lostmsu** [TimDettmers/bitsandbytes#88]
Currently I get

> Gradient+optimizer bit data type combination not supported: grad torch.bfloat16, optimizer torch.uint8

**Comment by TimDettmers** [comment]
Thank you! This is an important feature that needs to be implemented. Currently, it's a bit of a mess with all those different CUDA versions and bf support. The problem is that only specific combinations of CUDA + GPUs support bf16, and the library needs to be restructured to be able to be compiled for all of those cases. It causes a bit of a combinatorial explosion in libraries that need to be compiled, which makes it difficult to maintain the library.

If anyone wants to give it a shot, I am happy to work on this if you create a PR.

**Comment by KohakuBlueleaf** [comment]
@TimDettmers sorry for bothering you!
Is there any update for this enhancement?
really need bf16 weight + bf16 amp + 8bit optimizer for training some big model...

**Comment by TimDettmers** [comment]
Strange, I thought I implemented this. I will check this and update if necessary. Thanks for reporting that it is still not working.

**Comment by TimDettmers** [comment]
This has been addressed in 0.39.1 and should work now.
