### ISSUE TITLE
Cannot use int8

### ISSUE THREAD

**Issue by RiverDong** [TimDettmers/bitsandbytes#9]
I tried to use 8xA100 to run BLOOM. But I cannot do load_in_8bit. I tried to follow the instruction [here](https://gist.github.com/younesbelkada/073f0b7902cbed2cbff662996a74162e)  load the model by `model = AutoModelForCausalLM.from_pretrained(model_name, device_map='auto', load_in_8bit=True, max_memory=max_memory)` Basically, if I don't have max_memory=max_memory, then most memory would go the gpu:0 and then CUDA out of memory error. If I put max_memory=max_memory, it will throw 8-bit operation are not supported under CPU. 
<img width="991" alt="Screen Shot 2022-08-13 at 10 45 09 PM" src="https://user-images.githubusercontent.com/54600128/184524432-06afc3cb-0a08-4c5c-bb59-674dd05649c8.png">

**Comment by TimDettmers** [comment]
The error is a CUDA error. The CUDA setup script does not detect the right cuda/compute capability/Nvidia driver version and location and the CPU library is loaded which throws this error.

Can you please post the output from these commands:
```bash
printenv
which nvcc
python -m  bitsandbytes
ls /usr/local/cuda*
find $CONDA_PREFIX -name libcudart.so | xargs ls -l
```

**Comment by TimDettmers** [comment]
Looking again at this error, I realize the problem is likely that you set the memory threshold too low in the max_memory. You are currently using 3 GB per GPU, for a total of 24 GB across 8 GPUs, but BLOOM needs ~180 GB of GPU memory. You can set it to ~36GB if you have A100 with 40 GB memory (or higher if you have the 80 GB ones).

We will fix the error message to note that this error appears if not enough memory is allocated for the GPU.
