### ISSUE TITLE
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

### ISSUE THREAD

**Issue by Dreamweaveress** [TimDettmers/bitsandbytes#91]
Hello there,

Using Automatic1111 and added dreambooth extension. Now when running Dreambooth with 8bitAdam activated I get this error:

Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

`CUDA SETUP: Loading binary C:\Users\Us\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 8.1GB

  Total target lifetime optimization steps = 1000
 CPU: False Adam: True, Prec: fp16, Prior: False, Grad: True, TextTr: True
 Allocated: 3.8GB
 Reserved: 8.1GB

Steps:   0%|                                                                                                                                                                | 0/1000 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu`

**Comment by RoyHammerlin** [comment]
Exact same error here. I've seen the fix listed [here](https://github.com/TimDettmers/bitsandbytes/blob/main/errors_and_solutions.md#No-kernel-image-available) but have had no luck implementing it in Windows 10

**Comment by TimDettmers** [comment]
Thanks for reporting this error. @RoyHammerlin you found the instructions to fix this error, but it seems the instructions are insufficient to fix this issue for Windows 10. Could you help me figure it out? I do not have a Windows 10 install.

The main problem is a mismatch of the CUDA version required/loaded by PyTorch and the CUDA version needed by the physical GPU. This can usually be fixed by updating the CUDA version, but it might be that an old CUDA version is overriding the newer CUDA version, in which case a CUDA install will not solve the problem. So the solution should be

1. Remove old CUDA version
2. Install new CUDA version

It would be great if we would have some reliable instructions for how to do this on Windows 10. If you can figure this out and create a pull request, I will merge the windows 10 instructions to the file that you linked.
